### ISSUE TITLE
Dropdowns broken

### ISSUE THREAD

**Issue by JakeSidSmith** [dabapps/betta#68]
Dropdown section has nothing in it... that's because it's missing this bit of css.

``` css
.dropdown-menu {
  position: static;
  display: block;
  margin-bottom: 20px;
}
```
